baseurl: /coffeebrew_jekyll_paginate
theme: coffeebrew_jekyll_docs

exclude:
  - .git
  - .github
  - _versions/.keep
  - lib
  - pkg
  - script
  - spec
  - templates
  - .gitignore
  - .rspec
  - .rubocop.yml
  - .ruby-version
  - .tool-versions
  - CHANGELOG.md
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - Rakefile
  - coffeebrew_jekyll_paginate.gemspec

plugins:
  - jekyll-toc

toc:
  min_level: 2
  max_level: 3
  list_class: toc

coffeebrew_jekyll_docs:
  copyright: "Coffee Brew Apps"
  license:
    name: "MIT License"
    url: "/license.html"
  socials:
    - link: "https://github.com/coffeebrewapps/coffeebrew_jekyll_paginate"
      icon: "fa-brands fa-github"
    - link: "https://www.linkedin.com/company/coffeebrewapps/"
      icon: "fa-brands fa-linkedin"
    - link: "mailto:coffeebrewapps+hi@gmail.com"
      icon: "fa-solid fa-envelope"
  powered_by:
    host:
      link: "https://github.com"
      name: "Github Pages"

collections:
  versions:
    output: true

defaults:
  - scope:
      path: ""
    values:
      layout: default
      toc: true
  - scope:
      path: ""
      type: "versions"
    values:
      layout: version
