#!/usr/bin/env ruby

# frozen_string_literal: true

require "fileutils"

root_dir = File.expand_path("../", __dir__)

index_dest = File.join(root_dir, "index.md")
license_dest = File.join(root_dir, "license.md")
changelog_dest = File.join(root_dir, "versions.md")

FileUtils.rm_f(index_dest)
FileUtils.rm_f(license_dest)
FileUtils.rm_f(changelog_dest)
