#!/bin/bash
set -e

echo "RuboCop $(bundle exec rubocop --version)"
echo "Files to inspect: $(bundle exec rubocop -L)"
bundle exec rubocop -D -E $@
success=$?
if ((success != 0)); then
   echo -e "\nTry running \`script/lint -a\` to automatically fix errors"
fi
rm .rubocop-https*yml
exit $success
