# Reference: https://github.com/jekyll/minima/blob/master/.github/workflows/demo_site.yml
#
name: Build and Deploy Documentation Site

on:
  # Run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      build_version:
        description: "Build version"
        required: true

jobs:
  deploy_docs:
    runs-on: "ubuntu-latest"
    env:
      BUNDLE_PATH: "vendor/bundle"
      BUNDLE_JOBS: 4
      BUNDLE_RETRY: 3

    strategy:
      fail-fast: true
      matrix:
        ruby-version:
          - 3.2

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          repository: coffeebrewapps/coffeebrew_jekyll_paginate
          ref: main
      - name: "Set up Ruby ${{ matrix.ruby-version }}"
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby-version }}
          bundler-cache: true
      - name: Clone target branch
        run: |
          REMOTE_BRANCH="${REMOTE_BRANCH:-gh-pages}"
          REMOTE_REPO="https://${GITHUB_ACTOR}:${{ secrets.GITHUB_TOKEN }}@github.com/${GITHUB_REPOSITORY}.git"

          echo "Publishing to ${GITHUB_REPOSITORY} on branch ${REMOTE_BRANCH}"
          rm -rf _site/
          git clone --depth=1 --branch="${REMOTE_BRANCH}" --single-branch --no-checkout "${REMOTE_REPO}" _site/
      - name: Build site
        run: |
          script/docsbuild ${{ github.event.inputs.build_version }}
      - name: Deploy to GitHub Pages
        run: |
          SOURCE_COMMIT="$(git log -1 --pretty="%an: %B" "$GITHUB_SHA")"
          pushd _site &>/dev/null
          : > .nojekyll

          git add --all
          git -c user.name="${GITHUB_ACTOR}" -c user.email="${GITHUB_ACTOR}@users.noreply.github.com" \
            commit --quiet \
            --message "Deploy main from ${GITHUB_SHA}" \
            --message "$SOURCE_COMMIT"
          git push

          popd &>/dev/null
