name: Release Gem

on:
  workflow_dispatch:

jobs:
  release:
    if: "github.repository_owner == 'coffeebrewapps'"
    name: 'Release Gem (Ruby ${{ matrix.ruby-version }})'
    runs-on: ubuntu-latest
    env:
      BUNDLE_PATH: "vendor/bundle"
      BUNDLE_JOBS: 4
      BUNDLE_RETRY: 3

    strategy:
      fail-fast: true
      matrix:
        ruby-version:
          - 3.2

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: 'Set up Ruby ${{ matrix.ruby-version }}'
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby-version }}
          bundler-cache: true
      - name: Build and Publish Gem
        uses: ashmaroli/release-gem@dist
        with:
          gemspec_name: coffeebrew_jekyll_paginate
        env:
          GEM_HOST_API_KEY: ${{ secrets.RUBYGEMS_GEM_PUSH_API_KEY }}
